name: counter

dependencies:
  - python==3.8.5
  - pip
  - matplotlib
  - scipy
  # - PySide2
  - pyinstaller
  # - opencv-python
  - pyqtgraph
  # - qtmodern
  - lxml
  - tqdm
  - absl-py
  # - easydict
  - pillow
  - shapely
  - h5py
  # - hikvisionapi
  - 
    
