class Translator:
    def __init__(self):
        self.add_camera_btn = ''
        self.edit_camera_btn = ''
        self.remove_camera_btn = ''
        self.show_data_btn = ''
        self.use_video_checkbox = ''
        self.cars = ''
        self.buses = ''
        self.bicycles = ''
        self.motorcycles = ''
        self.trucks = ''
        self.a_in = ''
        self.b_in = ''
        self.c_in = ''
        self.d_in = ''
        self.a_out = ''
        self.b_out = ''
        self.c_out = ''
        self.d_out = ''
        self.start_inference_btn = ''
        self.stop_process_btn = ''

        # add camera window translations
        self.add_cam_window_title = ''
        self.add_cam_window_cam_ip = ''
        self.add_cam_window_cam_username = ''
        self.add_cam_window_cam_password = ''
        self.add_cam_window_cam_display_name = ''
        self.add_cam_window_add_cam_btn = ''
    
    def translateToEnglish(self):
        self.add_camera_btn = 'Add Camera'
        self.edit_camera_btn = 'Edit Camera'
        self.remove_camera_btn = 'Remove Camera'
        self.show_data_btn = 'Show Data'
        self.use_video_checkbox = 'Use Video'
        self.cars = 'Cars'
        self.buses = 'Buses'
        self.bicycles = 'Bicycles'
        self.motorcycles = 'Motorcycles'
        self.trucks = 'Trucks'
        self.a_in = 'A in'
        self.b_in = 'B in'
        self.c_in = 'C in'
        self.d_in = 'D in'
        self.a_out = 'A out'
        self.b_out = 'B out'
        self.c_out = 'C out'
        self.d_out = 'D out'
        self.start_inference_btn = 'START'
        self.stop_process_btn = 'STOP'

        # add camera window translations
        self.add_cam_window_title = 'Add Camera'
        self.add_cam_window_cam_ip = 'Camera IP'
        self.add_cam_window_cam_username = 'Username'
        self.add_cam_window_cam_password = 'Password'
        self.add_cam_window_cam_display_name = 'Display name'
        self.add_cam_window_add_cam_btn = 'Add Camera'
    
    def translateToUzbek(self):
        self.add_camera_btn = 'Kamera qo\'shish'
        self.edit_camera_btn = 'Kamerani o\'zgartirish'
        self.remove_camera_btn = 'Kamerani o\'chirish'
        self.show_data_btn = 'Ma\'lumotlarni ko\'rish'
        self.use_video_checkbox = 'Video ishlatish'
        self.cars = 'Yengil mashinalar'
        self.buses = 'Avtobuslar'
        self.bicycles = 'Velosipedlar'
        self.motorcycles = 'Motosikllar'
        self.trucks = 'Yuk mashinalari'
        self.a_in = 'A kirish'
        self.b_in = 'B kirish'
        self.c_in = 'C kirish'
        self.d_in = 'D kirish'
        self.a_out = 'A chiqish'
        self.b_out = 'B chiqish'
        self.c_out = 'C chiqish'
        self.d_out = 'D chiqish'
        self.start_inference_btn = 'BOSHLASH'
        self.stop_process_btn = 'TO\'XTATISH'

        # add camera window translations
        self.add_cam_window_title = 'Kamera qo\'shish'
        self.add_cam_window_cam_ip = 'IP'
        self.add_cam_window_cam_username = 'Foydalanuvchi nomi'
        self.add_cam_window_cam_password = 'Maxfiy so\'z'
        self.add_cam_window_cam_display_name = 'Kamera nomi'
        self.add_cam_window_add_cam_btn = 'Kamera qo\'shish'
